spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.36.43:3306/yuqing_manage_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: qidian
    password: qd2019B03

mybatis:
  type-aliases-package: com.boot.demo.entity
  mapper-locations: classpath:/dao/*
  configuration:
    mapUnderscoreToCamelCase: true